version: '3'

services:
  app:
    build: .
    container_name: url-shortener-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - app_db

  app_db:
    container_name: url-shortener-app-db
    image: postgres:14.11
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgresdb-app:/var/lib/postgresql/data

volumes:
  postgresdb-app:
