CREATE TABLE IF NOT EXISTS urls (
  id UUID DEFAULT gen_random_uuid(),
  short_url VARCHAR(255) UNIQUE NOT NULL,
  original_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
